# Generated by Django 4.2.2 on 2023-07-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auther_com',
            new_name='which_blog',
        ),
    ]
