# Generated by Django 4.2.2 on 2023-07-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_auther_com_comment_which_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_siled',
            field=models.BooleanField(default=True),
        ),
    ]
