# Generated by Django 4.2.2 on 2023-07-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_is_siled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_siled',
            new_name='is_slid',
        ),
    ]
