# Generated by Django 4.2.2 on 2023-07-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_is_siled_product_is_slid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stage',
            new_name='Faq',
        ),
        migrations.RenameModel(
            old_name='StageImg',
            new_name='FaqImg',
        ),
    ]
