# Generated by Django 4.2.2 on 2023-07-14 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_stage_faq_rename_stageimg_faqimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.faqimg'),
            preserve_default=False,
        ),
    ]
