# Generated by Django 4.2.2 on 2023-07-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='text',
        ),
    ]
