# Generated by Django 4.2.2 on 2023-07-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='cotegory',
            new_name='category',
        ),
    ]
